"use client";
import {useState} from "react";
export default function CheckoutPage(){
const [form,setForm]=useState({recipient_name:"",phone:"",postal_code:"",city:"",district:"",address_line:""});
const [message,setMessage]=useState("");
const [order,setOrder]=useState<any>(null);
const submit=async(e:React.FormEvent)=>{e.preventDefault();setMessage("建立訂單中…");const r=await fetch("/api/checkout",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({shippingAddress:form})});const d=await r.json();if(!r.ok){setMessage(d.error||"建立訂單失敗");return}setOrder(d.order);setMessage("")};
if(order)return <main className="page"><section className="hero"><p className="eyebrow">ORDER CREATED</p><h1>訂單已建立</h1><p>訂單編號：<strong>{order.order_number}</strong></p><h2>{"NT$"+order.total_twd.toLocaleString()}</h2><p>目前狀態：待付款。下一階段將接上 ECPay 真實付款。</p></section></main>;
return <main className="page"><section className="hero" style={{maxWidth:700}}><p className="eyebrow">CHECKOUT</p><h1>確認訂單</h1>{message&&<p>{message}</p>}<form onSubmit={submit}><label>收件人</label><input required value={form.recipient_name} onChange={e=>setForm({...form,recipient_name:e.target.value})} style={{display:"block",width:"100%",padding:14,margin:"8px 0 16px"}}/><label>手機</label><input required value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} style={{display:"block",width:"100%",padding:14,margin:"8px 0 16px"}}/><label>郵遞區號</label><input value={form.postal_code} onChange={e=>setForm({...form,postal_code:e.target.value})} style={{display:"block",width:"100%",padding:14,margin:"8px 0 16px"}}/><label>城市</label><input required value={form.city} onChange={e=>setForm({...form,city:e.target.value})} style={{display:"block",width:"100%",padding:14,margin:"8px 0 16px"}}/><label>區</label><input value={form.district} onChange={e=>setForm({...form,district:e.target.value})} style={{display:"block",width:"100%",padding:14,margin:"8px 0 16px"}}/><label>地址</label><input required value={form.address_line} onChange={e=>setForm({...form,address_line:e.target.value})} style={{display:"block",width:"100%",padding:14,margin:"8px 0 20px"}}/><button type="submit" style={{padding:"15px 28px",border:0,borderRadius:12,fontWeight:800}}>確認建立訂單</button></form></section></main>;
}