export const GIFT_COLLECTIONS = [
  {
    slug: "portrait-for-mom",
    name: "送給媽媽",
    subtitle: "把家人的溫暖，留在她每天看見的地方。",
    image: "family-portrait",
    categories: ["Family", "Art"],
  },
  {
    slug: "portrait-for-dad",
    name: "送給爸爸",
    subtitle: "為他喜歡的人、寵物與生活故事，找到專屬畫作。",
    image: "dog-portrait",
    categories: ["Pets", "Vehicles"],
  },
  {
    slug: "portrait-for-wife",
    name: "送給妻子",
    subtitle: "用一張重要的照片，說出一直放在心裡的話。",
    image: "anniversary-portrait",
    categories: ["Couples", "Wedding"],
  },
  {
    slug: "portrait-for-girlfriend",
    name: "送給女友",
    subtitle: "把兩個人的日常，變成值得珍藏的驚喜。",
    image: "couple-portrait",
    categories: ["Couples", "Art"],
  },
  {
    slug: "portrait-for-boyfriend",
    name: "送給男友",
    subtitle: "挑選屬於他的個性與色彩。",
    image: "car-portrait",
    categories: ["Cartoon", "Vehicles"],
  },
  {
    slug: "portrait-for-grandparents",
    name: "送給祖父母",
    subtitle: "讓一家人的合照，成為家裡最溫暖的角落。",
    image: "family-portrait",
    categories: ["Family", "Portrait"],
  },
] as const;
export const OCCASION_COLLECTIONS = [
  {
    slug: "christmas-portrait-gift",
    name: "聖誕節",
    subtitle: "把節日裡的團聚，做成一份溫暖的藝術禮物。",
    image: "storybook-family-portrait",
    categories: ["Family", "Pets"],
  },
  {
    slug: "valentines-portrait",
    name: "情人節",
    subtitle: "讓你們的合照，有另一種浪漫的模樣。",
    image: "couple-portrait",
    categories: ["Couples", "Art"],
  },
  {
    slug: "mothers-day-portrait",
    name: "母親節",
    subtitle: "送給媽媽一幅充滿家人回憶的畫。",
    image: "family-portrait",
    categories: ["Family", "Art"],
  },
  {
    slug: "fathers-day-portrait",
    name: "父親節",
    subtitle: "從他喜歡的生活片段，開始一份用心的禮物。",
    image: "car-portrait",
    categories: ["Vehicles", "Pets"],
  },
  {
    slug: "anniversary",
    name: "週年紀念",
    subtitle: "把陪伴的歲月，化成可以看見的藝術。",
    image: "anniversary-portrait",
    categories: ["Couples", "Wedding"],
  },
  {
    slug: "wedding",
    name: "婚禮",
    subtitle: "留下兩個人重要的一天。",
    image: "wedding-portrait",
    categories: ["Wedding", "Couples"],
  },
  {
    slug: "graduation",
    name: "畢業",
    subtitle: "為新的開始，留下這一刻的自信與笑容。",
    image: "graduation-portrait",
    categories: ["Portrait", "Cartoon"],
  },
  {
    slug: "first-home",
    name: "新居落成",
    subtitle: "用家的輪廓，裝飾新的生活。",
    image: "house-portrait",
    categories: ["Home", "Art"],
  },
  {
    slug: "new-baby",
    name: "寶寶誕生",
    subtitle: "把第一張家庭照片，做成溫柔的紀念。",
    image: "baby-portrait",
    categories: ["Family", "Portrait"],
  },
  {
    slug: "memorial",
    name: "思念紀念",
    subtitle: "用細膩的畫作，收藏珍愛的人與陪伴。",
    image: "memorial-portrait",
    categories: ["Portrait", "Pets"],
  },
] as const;
