export const REFERENCE_GALLERY = [
  {
    key: "simpsons-portrait",
    name: "Simpsons Portrait",
    category: "Cartoon",
    src: "/images/reference/styles/simpsons-portrait-thumb.webp",
  },
  {
    key: "anime-portrait",
    name: "Anime Portrait",
    category: "Cartoon",
    src: "/images/reference/styles/anime-portrait-thumb.webp",
  },
  {
    key: "pet-portrait",
    name: "Pet Portrait",
    category: "Pets",
    src: "/images/reference/styles/pet-portrait-thumb.webp",
  },
  {
    key: "cartoon-portrait",
    name: "Cartoon Portrait",
    category: "Cartoon",
    src: "/images/reference/styles/cartoon-portrait-thumb.webp",
  },
  {
    key: "pop-art-portrait",
    name: "Pop Art Portrait",
    category: "Art",
    src: "/images/reference/styles/pop-art-portrait-thumb.webp",
  },
  {
    key: "comic-book-portrait",
    name: "Comic Book Portrait",
    category: "Cartoon",
    src: "/images/reference/styles/comic-book-portrait-thumb.webp",
  },
  {
    key: "couple-portrait",
    name: "Couple Portrait",
    category: "Couples",
    src: "/images/reference/styles/couple-portrait-thumb.webp",
  },
  {
    key: "custom-portrait",
    name: "Custom Portrait",
    category: "Portrait",
    src: "/images/reference/styles/custom-portrait-thumb.webp",
  },
  {
    key: "digital-portrait",
    name: "Digital Portrait",
    category: "Portrait",
    src: "/images/reference/styles/digital-portrait-thumb.webp",
  },
  {
    key: "family-portrait",
    name: "Family Portrait",
    category: "Family",
    src: "/images/reference/styles/family-portrait-thumb.webp",
  },
  {
    key: "photo-to-art",
    name: "Photo to Art",
    category: "Art",
    src: "/images/reference/styles/photo-to-art-thumb.webp",
  },
  {
    key: "pixel-art-portrait",
    name: "Pixel Art Portrait",
    category: "Cartoon",
    src: "/images/reference/styles/pixel-art-portrait-thumb.webp",
  },
  {
    key: "portrait-gift",
    name: "Portrait Gift",
    category: "Gifts",
    src: "/images/reference/styles/portrait-gift-thumb.webp",
  },
  {
    key: "renaissance-portrait",
    name: "Renaissance Portrait",
    category: "Art",
    src: "/images/reference/styles/renaissance-portrait-thumb.webp",
  },
  {
    key: "watercolor-portrait",
    name: "Watercolor Portrait",
    category: "Art",
    src: "/images/reference/styles/watercolor-portrait-thumb.webp",
  },
  {
    key: "wedding-portrait",
    name: "Wedding Portrait",
    category: "Wedding",
    src: "/images/reference/styles/wedding-portrait-thumb.webp",
  },
  {
    key: "canvas-print",
    name: "Canvas Print",
    category: "Portrait",
    src: "/images/reference/styles/canvas-print-thumb.webp",
  },
  {
    key: "dog-portrait",
    name: "Dog Portrait",
    category: "Pets",
    src: "/images/reference/styles/dog-portrait-thumb.webp",
  },
  {
    key: "cat-portrait",
    name: "Cat Portrait",
    category: "Pets",
    src: "/images/reference/styles/cat-portrait-thumb.webp",
  },
  {
    key: "horse-portrait",
    name: "Horse Portrait",
    category: "Pets",
    src: "/images/reference/styles/horse-portrait-thumb.webp",
  },
  {
    key: "royal-pet-portrait",
    name: "Royal Pet Portrait",
    category: "Pets",
    src: "/images/reference/styles/royal-pet-portrait-thumb.webp",
  },
  {
    key: "pet-memorial-portrait",
    name: "Pet Memorial Portrait",
    category: "Pets",
    src: "/images/reference/styles/pet-memorial-portrait-thumb.webp",
  },
  {
    key: "family-illustration",
    name: "Family Illustration",
    category: "Family",
    src: "/images/reference/styles/family-illustration-thumb.webp",
  },
  {
    key: "storybook-family-portrait",
    name: "Storybook Family Portrait",
    category: "Family",
    src: "/images/reference/styles/storybook-family-portrait-thumb.webp",
  },
  {
    key: "couple-line-art-portrait",
    name: "Couple Line Art Portrait",
    category: "Couples",
    src: "/images/reference/styles/couple-line-art-portrait-thumb.webp",
  },
  {
    key: "wedding-line-art-portrait",
    name: "Wedding Line Art Portrait",
    category: "Wedding",
    src: "/images/reference/styles/wedding-line-art-portrait-thumb.webp",
  },
  {
    key: "wedding-venue-portrait",
    name: "Wedding Venue Portrait",
    category: "Wedding",
    src: "/images/reference/styles/wedding-venue-portrait-thumb.webp",
  },
  {
    key: "wedding-bouquet-illustration",
    name: "Wedding Bouquet Illustration",
    category: "Wedding",
    src: "/images/reference/styles/wedding-bouquet-illustration-thumb.webp",
  },
  {
    key: "save-the-date-illustration",
    name: "Save the Date Illustration",
    category: "Wedding",
    src: "/images/reference/styles/save-the-date-illustration-thumb.webp",
  },
  {
    key: "house-portrait",
    name: "House Portrait",
    category: "Home",
    src: "/images/reference/styles/house-portrait-thumb.webp",
  },
  {
    key: "first-home-illustration",
    name: "First Home Illustration",
    category: "Home",
    src: "/images/reference/styles/first-home-illustration-thumb.webp",
  },
  {
    key: "watercolor-house-portrait",
    name: "Watercolor House Portrait",
    category: "Home",
    src: "/images/reference/styles/watercolor-house-portrait-thumb.webp",
  },
  {
    key: "memorial-portrait",
    name: "Memorial Portrait",
    category: "Gifts",
    src: "/images/reference/styles/memorial-portrait-thumb.webp",
  },
  {
    key: "baby-portrait",
    name: "Baby Portrait",
    category: "Gifts",
    src: "/images/reference/styles/baby-portrait-thumb.webp",
  },
  {
    key: "graduation-portrait",
    name: "Graduation Portrait",
    category: "Gifts",
    src: "/images/reference/styles/graduation-portrait-thumb.webp",
  },
  {
    key: "anniversary-portrait",
    name: "Anniversary Portrait",
    category: "Gifts",
    src: "/images/reference/styles/anniversary-portrait-thumb.webp",
  },
  {
    key: "baby-birth-stat-poster",
    name: "Baby Birth Stat Poster",
    category: "Gifts",
    src: "/images/reference/styles/baby-birth-stat-poster-thumb.webp",
  },
  {
    key: "nursery-name-print",
    name: "Nursery Name Print",
    category: "Gifts",
    src: "/images/reference/styles/nursery-name-print-thumb.webp",
  },
  {
    key: "ghibli-portrait",
    name: "Ghibli Style Portrait",
    category: "Art",
    src: "/images/reference/styles/ghibli-portrait-thumb.webp",
  },
  {
    key: "oil-painting-portrait",
    name: "Oil Painting Portrait",
    category: "Art",
    src: "/images/reference/styles/oil-painting-portrait-thumb.webp",
  },
  {
    key: "minimalist-line-art-portrait",
    name: "Minimalist Line Art Portrait",
    category: "Art",
    src: "/images/reference/styles/minimalist-line-art-portrait-thumb.webp",
  },
  {
    key: "pencil-sketch-portrait",
    name: "Pencil Sketch Portrait",
    category: "Art",
    src: "/images/reference/styles/pencil-sketch-portrait-thumb.webp",
  },
  {
    key: "stained-glass-portrait",
    name: "Stained Glass Portrait",
    category: "Art",
    src: "/images/reference/styles/stained-glass-portrait-thumb.webp",
  },
  {
    key: "boho-line-art-portrait",
    name: "Boho Line Art Portrait",
    category: "Art",
    src: "/images/reference/styles/boho-line-art-portrait-thumb.webp",
  },
  {
    key: "cyberpunk-portrait",
    name: "Cyberpunk Portrait",
    category: "Art",
    src: "/images/reference/styles/cyberpunk-portrait-thumb.webp",
  },
  {
    key: "pixar-portrait",
    name: "3D Animated Portrait",
    category: "Cartoon",
    src: "/images/reference/styles/pixar-portrait-thumb.webp",
  },
  {
    key: "superhero-portrait",
    name: "Superhero Portrait",
    category: "Cartoon",
    src: "/images/reference/styles/superhero-portrait-thumb.webp",
  },
  {
    key: "lego-portrait",
    name: "Minifigure Portrait",
    category: "Cartoon",
    src: "/images/reference/styles/lego-portrait-thumb.webp",
  },
  {
    key: "caricature-portrait",
    name: "Caricature Portrait",
    category: "Cartoon",
    src: "/images/reference/styles/caricature-portrait-thumb.webp",
  },
  {
    key: "faceless-portrait",
    name: "Faceless Portrait",
    category: "Art",
    src: "/images/reference/styles/faceless-portrait-thumb.webp",
  },
  {
    key: "gta-style-portrait",
    name: "GTA Style Portrait",
    category: "Cartoon",
    src: "/images/reference/styles/gta-style-portrait-thumb.webp",
  },
  {
    key: "steampunk-portrait",
    name: "Steampunk Portrait",
    category: "Art",
    src: "/images/reference/styles/steampunk-portrait-thumb.webp",
  },
  {
    key: "rick-and-morty-portrait",
    name: "Rick & Morty Portrait",
    category: "Cartoon",
    src: "/images/reference/styles/rick-and-morty-portrait-thumb.webp",
  },
  {
    key: "south-park-portrait",
    name: "South Park Portrait",
    category: "Cartoon",
    src: "/images/reference/styles/south-park-portrait-thumb.webp",
  },
  {
    key: "family-guy-portrait",
    name: "Family Guy Portrait",
    category: "Cartoon",
    src: "/images/reference/styles/family-guy-portrait-thumb.webp",
  },
  {
    key: "futurama-portrait",
    name: "Futurama Portrait",
    category: "Cartoon",
    src: "/images/reference/styles/futurama-portrait-thumb.webp",
  },
  {
    key: "bobs-burgers-portrait",
    name: "Bob's Burgers Portrait",
    category: "Cartoon",
    src: "/images/reference/styles/bobs-burgers-portrait-thumb.webp",
  },
  {
    key: "archer-portrait",
    name: "Archer Portrait",
    category: "Cartoon",
    src: "/images/reference/styles/archer-portrait-thumb.webp",
  },
  {
    key: "car-portrait",
    name: "Car Portrait",
    category: "Vehicles",
    src: "/images/reference/styles/car-portrait-thumb.webp",
  },
  {
    key: "motorcycle-portrait",
    name: "Motorcycle Portrait",
    category: "Vehicles",
    src: "/images/reference/styles/motorcycle-portrait-thumb.webp",
  },
  {
    key: "boat-portrait",
    name: "Boat Portrait",
    category: "Vehicles",
    src: "/images/reference/styles/boat-portrait-thumb.webp",
  },
  {
    key: "victorian-portrait",
    name: "Victorian Portrait",
    category: "Art",
    src: "/images/reference/styles/victorian-portrait-thumb.webp",
  },
  {
    key: "medieval-knight-portrait",
    name: "Medieval Knight Portrait",
    category: "Art",
    src: "/images/reference/styles/medieval-knight-portrait-thumb.webp",
  },
  {
    key: "watercolor-dog-portrait",
    name: "Watercolor Dog Portrait",
    category: "Art",
    src: "/images/reference/styles/watercolor-portrait-2.webp",
  },
  {
    key: "watercolor-cat-portrait",
    name: "Watercolor Cat Portrait",
    category: "Art",
    src: "/images/reference/styles/watercolor-portrait-3.webp",
  },
  {
    key: "watercolor-couple-portrait",
    name: "Watercolor Couple Portrait",
    category: "Couples",
    src: "/images/reference/styles/watercolor-portrait-4.webp",
  },
  {
    key: "watercolor-family-portrait",
    name: "Watercolor Family Portrait",
    category: "Family",
    src: "/images/reference/styles/watercolor-portrait-5.webp",
  },
  {
    key: "anime-dog-portrait",
    name: "Anime Dog Portrait",
    category: "Pets",
    src: "/images/reference/styles/anime-portrait-2.webp",
  },
  {
    key: "anime-cat-portrait",
    name: "Anime Cat Portrait",
    category: "Pets",
    src: "/images/reference/styles/anime-portrait-3.webp",
  },
  {
    key: "anime-couple-portrait",
    name: "Anime Couple Portrait",
    category: "Couples",
    src: "/images/reference/styles/anime-portrait-4.webp",
  },
  {
    key: "anime-family-portrait",
    name: "Anime Family Portrait",
    category: "Family",
    src: "/images/reference/styles/anime-portrait-5.webp",
  },
  {
    key: "golden-retriever-portrait",
    name: "Golden Retriever Portrait",
    category: "Pets",
    src: "/images/reference/landing/golden-retriever-portrait/golden-retriever-portrait-hero-bg.webp",
  },
  {
    key: "french-bulldog-portrait",
    name: "French Bulldog Portrait",
    category: "Pets",
    src: "/images/reference/landing/french-bulldog-portrait/french-bulldog-portrait-hero-bg.webp",
  },
  {
    key: "maine-coon-portrait",
    name: "Maine Coon Portrait",
    category: "Pets",
    src: "/images/reference/landing/maine-coon-portrait/maine-coon-portrait-hero-bg.webp",
  },
  {
    key: "persian-cat-portrait",
    name: "Persian Cat Portrait",
    category: "Pets",
    src: "/images/reference/landing/persian-cat-portrait/persian-cat-portrait-hero-bg.webp",
  },
  {
    key: "anniversary-oil-painting-portrait",
    name: "Anniversary Oil Painting Portrait",
    category: "Gifts",
    src: "/images/reference/styles/anniversary-portrait-thumb.webp",
  },
  {
    key: "newborn-family-portrait",
    name: "Newborn Family Portrait",
    category: "Gifts",
    src: "/images/reference/styles/baby-portrait-thumb.webp",
  },
  {
    key: "couples-portrait",
    name: "Love Portrait",
    category: "Love Portrait",
    src: "/images/reference/main_thumbnail.webp",
  },
  {
    key: "gawai-portrait",
    name: "Gawai Dayak Portrait",
    category: "Gawai Dayak Portrait",
    src: "/images/reference/styles/gawai-portrait-thumb.webp",
  },
] as const;
